---
jobs:
- name: test-bump-tag
  public: true
  plan:

  - get: concourse-promote-test

  - task: example-thing-that-does-work
    config:
      inputs:
        - name: concourse-promote-test
      platform: linux
      image: docker:///busybox
      run:
        path: find
        args: [..]

  - put: concourse-promote-versions
    params: 
      bump: patch
      pre: staging

  - put: concourse-promote-test
    params:
      repository: concourse-promote-test
      tag: concourse-promote-versions/number
      only_tag: true

resources:
- name: concourse-promote-test
  type: git
  source:
    uri: git@github.com:jonty/concourse-promote-test.git
    branch: master
    private_key: {{private_key}}
      
- name: concourse-promote-versions
  type: semver
  source:
    driver: git
    uri: git@github.com:jonty/concourse-promote-versions.git
    branch: master
    file: staging_version
    private_key: {{private_key}}
